// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDyEParWsErrnLzZLoIPp7w3EibUkXxKA',
    appId: '1:894703779489:web:3f441f399cd74fe960fae0',
    messagingSenderId: '894703779489',
    projectId: 'storage-testing-e7b30',
    authDomain: 'storage-testing-e7b30.firebaseapp.com',
    storageBucket: 'storage-testing-e7b30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzejM6FCBaXfybfj6GZ8DUlZYR4Y1j2Y',
    appId: '1:894703779489:android:2462c9f161e6b59a60fae0',
    messagingSenderId: '894703779489',
    projectId: 'storage-testing-e7b30',
    storageBucket: 'storage-testing-e7b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYo0YBluNvpyRp5CmCmSkQDxTf5_0FKC8',
    appId: '1:894703779489:ios:cd8b1636ccc5c39f60fae0',
    messagingSenderId: '894703779489',
    projectId: 'storage-testing-e7b30',
    storageBucket: 'storage-testing-e7b30.appspot.com',
    iosBundleId: 'com.example.zyluAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYo0YBluNvpyRp5CmCmSkQDxTf5_0FKC8',
    appId: '1:894703779489:ios:0387e995e53186d960fae0',
    messagingSenderId: '894703779489',
    projectId: 'storage-testing-e7b30',
    storageBucket: 'storage-testing-e7b30.appspot.com',
    iosBundleId: 'com.example.zyluAssignment.RunnerTests',
  );
}
